### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tjjh89017** [tjjh89017/stunmesh-go#38]
- [ ] One shot command
- [ ] get wg info from wgctrl-go every time
- [ ]

**Comment by tjjh89017** [comment]
One shot command
Requried CLI args `-1` or `--oneshot`
Execute Publish and Establish 3 time for each, and exit with success

**Comment by tjjh89017** [comment]
update config yaml
Replace TOML style config to YAML style

**Comment by tjjh89017** [comment]
multiple wg support
Support the following configuration
```yaml
refresh_interval: "10m"
stun:
  address: stun.l.google.com:19032
cloudflare:
  api_key: "<Your API Key>"
  api_email: "<Your email>"
  zone_name: "<Your Domain>"
interfaces:
  wg1:
    name: wg1
  wg2:
    name: wg2
```
