### ISSUE TITLE
Add feature to use ping as watchdog

### ISSUE THREAD

**Issue by tjjh89017** [tjjh89017/stunmesh-go#79]
If failed, we should doube the ping interval before next ping.
and we need to setup an upper limitation

**Comment by tjjh89017** [comment]
```yaml
---
refresh_interval: "1m"
log:
  level: "debug"
interfaces:
  wg0:
    peers:
      "<PEER_NAME>":
        public_key: "<PUBLIC_KEY_IN_BASE64>"
  wg1:
    peers:
      "<PEER_NAME>":
        public_key: "<PUBLIC_KEY_IN_BASE64>"
      "<PEER_NAME>":
        public_key: "<PUBLIC_KEY_IN_BASE64>"
stun:
  address: "stun.l.google.com:19302"
cloudflare:
  api_token: "<API_TOKEN>"
  zone_name: "<ZONE_NAME>"
```

consider we have this config for stunmesh-go
and we add more config to decsribe how to ping module works.

```yaml
---
refresh_interval: "1m"
log:
  level: "debug"
interfaces:
  wg0:
    peers:
      "<PEER_NAME>":
        public_key: "<PUBLIC_KEY_IN_BASE64>"
  wg1:
    peers:
      "<PEER_NAME>":
        public_key: "<PUBLIC_KEY_IN_BASE64>"
      "<PEER_NAME2>":
        public_key: "<PUBLIC_KEY_IN_BASE64>"
        ping: "<REMOTE IP or something>"
stun:
  address: "stun.l.google.com:19302"
cloudflare:
  api_token: "<API_TOKEN>"
  zone_name: "<ZONE_NAME>"
```

wg1 PEER_NAME2 has a ping config to ping another IP to check the wg connection.
If ping failed for 3 attempts, stunmesh-go should try to re-establish and re-publish for that peer again.
And if failed again, we should double the interval for re-establish and re-publish for that peer until the interval is greater or equal to the "refresh_interval"

For example, if ping failed, we should do re-establish and re-publish immediately.
Failed 2, we should wait 1 sec before do second time.
Failed 3, we should wait 2 sec.
Failed 4, we should wait 4 sec.
until X >= refresh_interval

ping module should be performed by stunmesh-go itself without other program.
And need to bind interface to wg1 interface for specific ping request/response.
something like the following command
```
ping -I wg1 XXXXX -c YYY
```

Need some discussion for this issue.
Design is not settled down yet.
